Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/01/2022
Var
// Seção de Declarações das variáveis
contador: Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
contador<- 0
Enquanto contador < 10 faca
    contador<- contador + 1
    Escreval (contador)
FimEnquanto

Fimalgoritmo